spring:
  profiles:
    active:
      - dev

---
server: 
  port: 4002

spring:
  profiles: dev
  application:
    name: microservice-consumer4002

eureka:
  client:
    register-with-eureka: false
    service-url: 
      defaultZone: http://eureka9003.com:9003/eureka/,http://eureka9002.com:9002/eureka/,http://eureka9001.com:9001/eureka/

---
server: 
  port: 4003

spring:
  profiles: test
  application:
    name: microservice-consumer4003

eureka:
  client:
    register-with-eureka: false
    service-url: 
      defaultZone: http://eureka9003.com:9003/eureka/,http://eureka9002.com:9002/eureka/,http://eureka9001.com:9001/eureka/