
server:
  port: 4001
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JockChenQiBin/microservice-config.git
          username: 568370928@qq.com
          password: cqb999520710
          skip-ssl-validation: true
